// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCzaShJqFzFsUo7kztpwynB0U-xYbOTvI',
    appId: '1:815408425605:web:31b345b83bcfa070ab97ec',
    messagingSenderId: '815408425605',
    projectId: 'tickly-d712b',
    authDomain: 'tickly-d712b.firebaseapp.com',
    storageBucket: 'tickly-d712b.appspot.com',
    measurementId: 'G-XZTV4XVK7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQCkuvtky7skFNxslpwYooBSCA-S4lO1E',
    appId: '1:815408425605:android:fb0cbe442db2e738ab97ec',
    messagingSenderId: '815408425605',
    projectId: 'tickly-d712b',
    storageBucket: 'tickly-d712b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxQVV0y0UlyxxvWvTVUTy82nND8nYCsXs',
    appId: '1:815408425605:ios:90f3406ea02e9a52ab97ec',
    messagingSenderId: '815408425605',
    projectId: 'tickly-d712b',
    storageBucket: 'tickly-d712b.appspot.com',
    iosBundleId: 'com.example.tickly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxQVV0y0UlyxxvWvTVUTy82nND8nYCsXs',
    appId: '1:815408425605:ios:90f3406ea02e9a52ab97ec',
    messagingSenderId: '815408425605',
    projectId: 'tickly-d712b',
    storageBucket: 'tickly-d712b.appspot.com',
    iosBundleId: 'com.example.tickly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCzaShJqFzFsUo7kztpwynB0U-xYbOTvI',
    appId: '1:815408425605:web:0b002384c87c6079ab97ec',
    messagingSenderId: '815408425605',
    projectId: 'tickly-d712b',
    authDomain: 'tickly-d712b.firebaseapp.com',
    storageBucket: 'tickly-d712b.appspot.com',
    measurementId: 'G-3H92JYGXY5',
  );
}
